
add_newline = false

format = "$all$shlvl$character"

right_format = """$cmd_duration"""

[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = 'â¯'
repeat_offset = 1
threshold = 0

[line_break]
disabled = true

[aws]
symbol = "îŒ½  "
format = '[$symbol($profile)(\($region\)) ($duration)]($style)'

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "
format = ' [$symbol]($style)'

[conda]
symbol = "ï„Œ "
format = ' [$symbol$environment]($style)'

[crystal]
symbol = "î˜¯ "
format = ' [$symbol]($style)'

[dart]
symbol = "î˜ "
format = ' [$symbol]($style)'

[directory]
fish_style_pwd_dir_length = 1
read_only = " ó°Œ¾"
format = '[$path]($style)[$read_only]($read_only_style)'

[docker_context]
symbol = "ïŒˆ "
format = ' [$symbol$context]($style)'

[elixir]
symbol = "î˜­ "
format = ' [$symbol]($style)'

[elm]
symbol = "î˜¬ "
format = ' [$symbol]($style)'

[fennel]
symbol = "îš¯ "
format = ' [$symbol]($style)'

[fossil_branch]
symbol = "ï˜ "
format = ' [$symbol$branch]($style)'

[git_branch]
symbol = "ï˜"
format = ' [$symbol $branch]($style) '

[git_commit]
tag_symbol = ' ï’ '

[golang]
symbol = "î˜§ "
format = ' [$symbol]($style)'

[guix_shell]
symbol = "ïŒ¥ "
format = ' [$symbol]($style)'

[haskell]
symbol = "î· "
format = ' [$symbol]($style)'

[haxe]
symbol = "î™¦ "
format = ' [$symbol]($style)'

[hg_branch]
symbol = "ï˜ "
format = ' [$symbol$branch]($style)'

[hostname]
ssh_symbol = "î¬ "

[java]
symbol = "î‰– "
format = ' [$symbol]($style)'

[julia]
symbol = "î˜¤ "
format = ' [$symbol]($style)'

[kotlin]
symbol = "î˜´ "
format = ' [$symbol]($style)'

[lua]
symbol = "î˜  "
format = ' [$symbol]($style)'

[memory_usage]
symbol = "ó°› "
format = ' $symbol[$ram( | $swap)]($style)'

[meson]
symbol = "ó°”· "
format = ' [$symbol$project]($style)'

[nim]
symbol = "ó°†¥ "
format = ' [$symbol]($style)'

[nix_shell]
symbol = "ïŒ“ "
format = ' [$symbol$state( \($name\))]($style)'

[nodejs]
symbol = "îœ˜ "
format = ' [$symbol]($style)'

[ocaml]
symbol = "î™º "
format = ' [$symbol(\($switch_indicator$switch_name\))]($style)'

[os]
format = ' [$symbol]($style)'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "
format = ' [$symbol]($style)'

[perl]
symbol = "î™¾ "
format = ' [$symbol]($style)'

[php]
symbol = "î˜ˆ "
format = ' [$symbol]($style)'

[pijul_channel]
symbol = "ï˜ "
format = ' [$symbol$channel]($style)'

[python]
symbol = "îˆµ "
format = ' [${symbol}${pyenv_prefix}(\($virtualenv\))]($style)'

[rlang]
symbol = "ó°Ÿ” "

[ruby]
symbol = "î‘ "
format = ' [$symbol]($style)'

[rust]
symbol = "ó±˜— "
format = ' [$symbol]($style)'

[scala]
symbol = "îœ· "
format = ' [$symbol]($style)'

[swift]
symbol = "î• "
format = ' [$symbol]($style)'

[zig]
symbol = "îš© "
format = ' [$symbol]($style)'

[gradle]
symbol = "î™  "
format = ' [$symbol]($style)'

[bun]
format = ' [$symbol]($style)'

[cmake]
format = ' [$symbol]($style)'

[cmd_duration]
format = '[$duration]($style)'
show_notifications = false
min_time_to_notify = 30_000

[cobol]
format = ' [$symbol]($style)'

[daml]
format = ' [$symbol]($style)'

[deno]
format = ' [$symbol]($style)'

[dotnet]
format = ' [$symbol(ğŸ¯ $tfm)]($style)'

[erlang]
format = ' [$symbol]($style)'

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\))]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style))'

[helm]
format = ' [$symbol]($style)'

[kubernetes]
format = ' [$symbol$context( \($namespace\))]($style)'

[opa]
format = ' [$symbol]($style)'

[openstack]
format = ' [$symbol$cloud(\($project\))]($style)'

[pulumi]
format = ' [$symbol$stack]($style)'

[purescript]
format = ' [$symbol]($style)'

[raku]
format = ' [$symbol]($style)'

[red]
format = ' [$symbol]($style)'

[spack]
format = ' [$symbol$environment]($style)'

[sudo]
format = ' [as $symbol]($style)'

[terraform]
format = ' [$symbol$workspace]($style)'

[time]
format = ' [$time]($style)'

[username]
format = ' [$user]($style)'

[vagrant]
format = ' [$symbol]($style)'

[vlang]
format = ' [$symbol]($style)'

[solidity]
format = ' [$symbol]($style)'
